# This workflow runs a spell check on all markdown files in the repository.
name: Spell Check

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  # Allow manual triggering
  workflow_dispatch:
  # Run weekly to catch any new issues
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache PySpelling Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pyspelling-${{ hashFiles('.github/spellcheck.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-pyspelling-
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspelling pymdown-extensions
      
      - name: Run Spellcheck
        id: spellcheck
        uses: rojopolis/spellcheck-github-actions@0.33.0
        with:
          config_path: .github/spellcheck.yaml
          task_name: Markdown
          output_file: spellcheck-output.txt
        continue-on-error: true
      
      - name: Create GitHub Issue for Spelling Errors
        if: ${{ steps.spellcheck.outcome == 'failure' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPELLCHECK_ERRORS: ${{ steps.spellcheck.outputs.output }}
        with:
          filename: .github/ISSUE_TEMPLATE/spelling-errors.md
          update_existing: true
          search_existing: open